global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "alert.rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'mstbl-blockchain'
    static_configs:
      - targets: ['mstbl-blockchain:26657']
    metrics_path: /metrics
    scrape_interval: 30s

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['mstbl-node1-exporter:9100']
    scrape_interval: 30s

  - job_name: 'mstbl-api'
    static_configs:
      - targets: ['mstbl-blockchain:1317']
    metrics_path: /metrics
    scrape_interval: 30s
